/**
 * Every axis is one `data-*` attribute on the lab root; `lab.css` styles each
 * value independently, so any combination renders.
 */
export const AXES = {
  width: ['550', '30', '28', '26', '24'],
  font: ['100', '94', '88'],
  pad: ['16', '12', '10'],
  header: ['stacked', 'stacked-sm', 'inline'],
  date: ['footer', 'header'],
  reply: ['line', 'small', 'hidden'],
  text: ['full', 'clamp8', 'clamp5'],
  media: [
    'natural',
    'cap',
    'ratio-1',
    'ratio-43',
    'ratio-169',
    'ratio-21',
    'fit',
  ],
  place: ['inset', 'narrow', 'bleed-top', 'bleed-bottom', 'side'],
  grid: ['squares', 'cells-32', 'fixed', 'row'],
  quote: ['full', 'compact', 'side', 'text'],
  shell: ['border', 'tint', 'rail'],
} as const

export type Axis = keyof typeof AXES
export type Design = { [K in Axis]: (typeof AXES)[K][number] }

export const AXIS_HELP: Record<Axis, string> = {
  width: 'Card width in rem (fixed). 550 = today: shrink-to-fit, max 550px',
  font: 'Card font size, % of the note font size',
  pad: 'Card padding in px',
  header:
    'stacked 40px avatar, stacked 32px avatar, or one line with a 24px avatar',
  date: 'Date in the footer (with time), or short date at the end of the header (no footer)',
  reply: '"Replying to" line: normal, small, hidden',
  text: 'Body text: full, or clamped to 8 / 5 lines',
  media:
    'Single media: natural (max 32rem, contain), cap (max 20rem, cover), ratio-N (never taller than N, cover), fit (max 16rem, never cropped, box shrinks)',
  place:
    'Media placement: inset, narrow (75%), bleeding to the card top / bottom, or a side thumbnail (photos only)',
  grid: '2 to 4 media: squares, 3:2 cells, fixed total height, or a single row',
  quote:
    'Quoted post: full, compact (short media, 3 lines, no footer), side thumbnail, or text only',
  shell: 'Card shell: border, tint, or a left rail',
}

export const CURRENT: Design = {
  width: '550',
  font: '100',
  pad: '16',
  header: 'stacked',
  date: 'footer',
  reply: 'line',
  text: 'full',
  media: 'natural',
  place: 'inset',
  grid: 'squares',
  quote: 'full',
  shell: 'border',
}

function design(overrides: Partial<Design>): Design {
  return { ...CURRENT, ...overrides }
}

export const PRESETS = {
  '00-current': CURRENT,
  '01-narrower': design({
    width: '28',
    media: 'cap',
    grid: 'cells-32',
    quote: 'compact',
  }),
  '02-tidy': design({
    width: '26',
    pad: '12',
    header: 'stacked-sm',
    media: 'ratio-43',
    grid: 'fixed',
    quote: 'compact',
  }),
  '03-tidy-inline': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-43',
    grid: 'fixed',
    quote: 'compact',
  }),
  '04-cinema': design({
    width: '28',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-169',
    grid: 'fixed',
    quote: 'compact',
    reply: 'small',
  }),
  '05-no-crop': design({
    width: '26',
    pad: '12',
    header: 'stacked-sm',
    media: 'fit',
    grid: 'cells-32',
    quote: 'compact',
  }),
  '06-strip': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-21',
    grid: 'row',
    quote: 'text',
    reply: 'small',
  }),
  '07-side-thumb': design({
    width: '28',
    pad: '12',
    header: 'stacked-sm',
    media: 'ratio-169',
    place: 'side',
    grid: 'fixed',
    quote: 'side',
  }),
  '08-link-preview': design({
    width: '26',
    font: '94',
    pad: '12',
    header: 'inline',
    date: 'header',
    text: 'clamp5',
    media: 'ratio-169',
    place: 'side',
    grid: 'fixed',
    quote: 'text',
    reply: 'small',
  }),
  '09-poster-top': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-169',
    place: 'bleed-top',
    grid: 'fixed',
    quote: 'compact',
    reply: 'small',
  }),
  '10-poster-bottom': design({
    width: '26',
    pad: '12',
    header: 'stacked-sm',
    date: 'header',
    media: 'ratio-43',
    place: 'bleed-bottom',
    grid: 'fixed',
    quote: 'compact',
  }),
  '11-small-type': design({
    width: '24',
    font: '94',
    pad: '12',
    header: 'stacked-sm',
    media: 'ratio-43',
    grid: 'fixed',
    quote: 'compact',
    reply: 'small',
  }),
  '12-micro': design({
    width: '24',
    font: '88',
    pad: '10',
    header: 'inline',
    date: 'header',
    text: 'clamp8',
    media: 'ratio-169',
    grid: 'fixed',
    quote: 'text',
    reply: 'small',
  }),
  '13-narrow-media': design({
    width: '28',
    pad: '12',
    header: 'stacked-sm',
    date: 'header',
    media: 'ratio-43',
    place: 'narrow',
    grid: 'cells-32',
    quote: 'compact',
  }),
  '14-tint': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-43',
    grid: 'fixed',
    quote: 'compact',
    shell: 'tint',
    reply: 'small',
  }),
  '15-rail': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'fit',
    grid: 'cells-32',
    quote: 'compact',
    shell: 'rail',
    reply: 'small',
  }),
  '16-brief': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    text: 'clamp5',
    media: 'ratio-21',
    grid: 'row',
    quote: 'text',
    reply: 'hidden',
  }),
  '17-tint-poster': design({
    width: '26',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-169',
    place: 'bleed-top',
    grid: 'fixed',
    quote: 'compact',
    shell: 'tint',
    reply: 'small',
  }),
  '18-square-cap': design({
    width: '24',
    pad: '12',
    header: 'stacked-sm',
    date: 'header',
    media: 'ratio-1',
    grid: 'squares',
    quote: 'compact',
  }),
  '19-tint-side': design({
    width: '26',
    font: '94',
    pad: '12',
    header: 'inline',
    date: 'header',
    media: 'ratio-169',
    place: 'side',
    grid: 'fixed',
    quote: 'side',
    shell: 'tint',
    reply: 'small',
  }),
  '20-rail-brief': design({
    width: '26',
    font: '94',
    pad: '12',
    header: 'inline',
    date: 'header',
    text: 'clamp8',
    media: 'ratio-21',
    grid: 'row',
    quote: 'text',
    shell: 'rail',
    reply: 'small',
  }),
} satisfies Record<string, Design>

export type PresetName = keyof typeof PRESETS
