packages:
  - packages/*
  - apps/*

linkWorkspacePackages: deep
ignoreWorkspaceRootCheck: true
allowBuilds:
  esbuild: false
patchedDependencies:
  react-tweet@3.3.1: patches/react-tweet@3.3.1.patch
