name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ./.github/actions/setup
      - run: pnpm --filter @post-embed/elements exec playwright install --with-deps chromium firefox webkit
      - name: Build TypeScript project references
        run: pnpm run typecheck
      - name: Test
        run: pnpm run test:run
